### ISSUE TITLE
The dependencies of the project are not configured correctly.

### ISSUE THREAD

**Issue by andcuevas** [TransbankDevelopers/transbank-sdk-java-webpay-rest-example#19]
In the pom.xml file there is a SNAPSHOT dependency:

```
<dependency>
    <groupId>com.github.transbankdevelopers</groupId>
    <artifactId>transbank-sdk-java</artifactId>
    <version>1.7.0-SNAPSHOT</version>
</dependency>
```

But there is no ```<repository>``` configured for this SNAPSHOT. Therefore the dependency can't be resolved.
Changing the dependency to 1.6.1 doesn't work because the example code depends on the version 1.7.0-SNAPSHOT.

**Comment by steaerox** [comment]
Is there any news about it? I have the same problem as @andcuevas
